---
- name: Install Nginx
  yum:
    name: nginx
    state: present

- name: Start and enable Nginx
  systemd:
    name: nginx
    state: started
    enabled: yes

- name: Configure Nginx reverse proxy
  copy:
    dest: /etc/nginx/conf.d/myapp.conf
    content: |
      server {
          listen 80;
          server_name localhost;

          location / {
              proxy_pass http://localhost:{{ app_port }};
              proxy_http_version 1.1;
              proxy_set_header Upgrade $http_upgrade;
              proxy_set_header Connection 'upgrade';
              proxy_set_header Host $host;
              proxy_cache_bypass $http_upgrade;
          }
      }
  notify:
    - Reload Nginx

handlers:
  - name: Reload Nginx
    systemd:
      name: nginx
      state: reloaded
...