---
- name: Deploy Node.js app
  hosts: app1
  become: yes
  vars:
    app_directory: /home/centos/devops-api
    repo_url: https://github.com/preye419/newgroup38.git
    app_port: 3000

  tasks:
    - name: Create app directory
      file:
        path: "{{ app_directory }}"
        state: directory
        owner: centos  # Ensure owner is centos
        group: centos  # Ensure group is centos
        mode: '0755'

    - name: Clone the application code
      git:
        repo: "{{ repo_url }}"
        dest: "{{ app_directory }}"
        version: main
        force: yes  # Ensures the repository is updated
      become: yes
      
    - name: Install Node.js if not installed
      yum:
        name: nodejs
        state: present
        become: yes

    - name: Install app dependencies
      npm:
        path: "{{ app_directory }}"
        state: present
        production: yes
        executable: /usr/bin/npm  # Optional: Specify the path to npm if not in the default location

    - name: Ensure the app is running
      shell: |
        cd {{ app_directory }}
        nohup npm start &
      args:
        chdir: "{{ app_directory }}"
        background: yes
        creates: "{{ app_directory }}/node_modules"  # Prevents rerunning if node_modules already exist

...