---
- name: Deploy Node.js App with Nginx
  hosts: app1
  become: yes

  vars:
    app_directory: /var/www/myapp
    repo_url: https://github.com/preye419/newgroup38.git

  roles:
    - deploy_app
...