---
- name: Remove existing MongoDB repo if it exists
  file:
    path: /etc/yum.repos.d/mongodb-org-5.0.repo
    state: absent
  ignore_errors: yes

- name: Add MongoDB 4.4 repo
  yum_repository:
    name: mongodb-org-4.4
    description: MongoDB Repository
    baseurl: https://repo.mongodb.org/yum/amazon/2/mongodb-org/4.4/x86_64/
    gpgcheck: yes
    enabled: yes
    gpgkey: https://www.mongodb.org/static/pgp/server-4.4.asc

- name: Install MongoDB 4.4
  yum:
    name: mongodb-org-4.4.29
    state: present

- name: Enable and start mongod
  systemd:
    name: mongod
    state: started
    enabled: yes
...