
---
- name: Add MongoDB 4.4 repo for CentOS 7
  copy:
    dest: /etc/yum.repos.d/mongodb-org-4.4.repo
    content: |
      [mongodb-org-4.4]
      name=MongoDB Repository
      baseurl=https://repo.mongodb.org/yum/redhat/7/mongodb-org/4.4/x86_64/
      gpgcheck=1
      enabled=1
      gpgkey=https://www.mongodb.org/static/pgp/server-4.4.asc

- name: Clean YUM cache
  command: yum clean all
  args:
    warn: false

- name: Make sure metadata is up to date
  command: yum makecache
  args:
    warn: false

- name: Install specific version of MongoDB 4.4
  yum:
    name:
      - mongodb-org-4.4.25
      - mongodb-org-server-4.4.25
      - mongodb-org-shell-4.4.25
      - mongodb-org-mongos-4.4.25
      - mongodb-org-tools-4.4.25
    state: present

- name: Enable and start MongoDB
  systemd:
    name: mongod
    enabled: yes
    state: started

...