
---
- name: Install and configure MongoDB on app1
  hosts: app1
  become: true
  tasks:

    - name: Install openssl10-libs (fixes MongoDB dependency issues)
      yum:
        name: openssl10-libs
        state: present

    - name: Add MongoDB 4.4 repo
      copy:
        dest: /etc/yum.repos.d/mongodb-org-4.4.repo
        content: |
          [mongodb-org-4.4]
          name=MongoDB Repository
          baseurl=https://repo.mongodb.org/yum/amazon/2/mongodb-org/4.4/x86_64/
          gpgcheck=1
          enabled=1
          gpgkey=https://www.mongodb.org/static/pgp/server-4.4.asc

    - name: Install MongoDB
      yum:
        name: mongodb-org
        state: present

    - name: Enable and start MongoDB
      systemd:
        name: mongod
        state: started
        enabled: true
...