---
- name: Add MongoDB 4.4 repo
  yum_repository:
    name: mongodb-org-4.4
    description: MongoDB Repository
    baseurl: https://repo.mongodb.org/yum/amazon/2/mongodb-org/4.4/x86_64/
    gpgcheck: yes
    enabled: yes
    gpgkey: https://www.mongodb.org/static/pgp/server-4.4.asc

- name: Install MongoDB 4.4
  yum:
    name:
      - mongodb-org-4.4.25
      - mongodb-org-server-4.4.25
      - mongodb-org-shell-4.4.25
      - mongodb-org-mongos-4.4.25
      - mongodb-org-tools-4.4.25
    state: present

- name: Enable and start mongod
  systemd:
    name: mongod
    state: started
    enabled: yes

...